/** Mockup metadata - mirrors lib/samples/index.ts (palette, labels). */
export const mockupSamples = {
  clinic: {
    name: "Family Clinic Booking Site",
    industry: "Clinic",
    business: "Meridian Family Clinic",
    city: "Thane",
    swatches: ["#fafbfa", "#3d8b7d", "#e8a13f"],
    dark: false,
  },
  jeweller: {
    name: "Jeweller Collection Catalogue",
    industry: "Jeweller",
    business: "Vasant & Sons",
    city: "Thane",
    swatches: ["#0f0d0a", "#c9a55c", "#f7f1e5"],
    dark: true,
  },
  ca: {
    name: "CA Practice Intake",
    industry: "CA / Professional",
    business: "Deshmukh & Associates",
    city: "Mumbai",
    swatches: ["#ffffff", "#1e3a6e", "#b8934a"],
    dark: false,
  },
  realty: {
    name: "Realty Listings Front Door",
    industry: "Real Estate",
    business: "Keystone Properties",
    city: "Thane",
    swatches: ["#f7f5f1", "#5b6b5e", "#c08a4e"],
    dark: false,
  },
  school: {
    name: "School Admissions Site",
    industry: "School",
    business: "Brightfield Academy",
    city: "Thane",
    swatches: ["#fdfbf6", "#2f5d8a", "#e08c3e"],
    dark: false,
  },
  travel: {
    name: "Tour Operator Package Site",
    industry: "Travel",
    business: "Sahyadri Trails",
    city: "Pune",
    swatches: ["#faf7f0", "#1f5c63", "#e5793a"],
    dark: false,
  },
  gym: {
    name: "Gym Trial Booking + Assistant",
    industry: "Gym",
    business: "Forge Strength Co.",
    city: "Thane",
    swatches: ["#101010", "#e13b3b", "#d4ff3f"],
    dark: true,
  },
  interior: {
    name: "Interior Design Portfolio",
    industry: "Interior Design",
    business: "Studio Kadam",
    city: "Mumbai",
    swatches: ["#f5f3ee", "#8a7a63", "#b5482e"],
    dark: false,
  },
  trader: {
    name: "Online Store + Assistant",
    industry: "Trader / D2C",
    business: "Nilaya Home",
    city: "Thane",
    swatches: ["#ffffff", "#2f6f5e", "#e8622e"],
    dark: false,
  },
  coaching: {
    name: "Coaching Classes Results Site",
    industry: "Coaching",
    business: "Summit Prep",
    city: "Thane",
    swatches: ["#FAF8FC", "#5B3A8E", "#E3B23C"],
    dark: false,
  },
};

export const allSlugs = Object.keys(mockupSamples);
